openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/v1"

paths:
  /list-all:
    get:
      operationId: TaskTracker.list_all
      tags:
        - list
      summary: "List all tasks and their statuses"
      responses:
        '200':
          